import Editor from '@monaco-editor/react'
import { AlertCircle, CheckCircle2, Code2, Lightbulb, LoaderCircle, RotateCcw, Send, Sparkles } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { ExplanationPanel } from '@/components/ExplanationPanel'
import { ErrorState } from '@/components/ui/ErrorState'
import { Modal } from '@/components/ui/Modal'
import { SectionHeader } from '@/components/ui/SectionHeader'
import { Select } from '@/components/ui/Select'
import { aiService } from '@/services/ai'
import type { AIChallengeResponse, AIFeedbackResponse, AIHintResponse, ChallengeDifficulty, ChallengeLanguage } from '@/types/ai'
import { readLearnerProgress, writeLearnerProgress } from '@/lib/learnerProgress'

const languages: Array<{ value: ChallengeLanguage; label: string; editor: string }> = [{ value: 'javascript', label: 'JavaScript', editor: 'javascript' }, { value: 'typescript', label: 'TypeScript', editor: 'typescript' }, { value: 'python', label: 'Python', editor: 'python' }, { value: 'java', label: 'Java', editor: 'java' }, { value: 'cpp', label: 'C++', editor: 'cpp' }, { value: 'csharp', label: 'C#', editor: 'csharp' }]
const buildTopics = (items: string[][]) => items.map(([value, label]) => ({ value, label }))
const fundamentals = [['variables', 'Variables'], ['conditionals', 'Conditionals'], ['loops', 'Loops'], ['functions', 'Functions'], ['arrays', 'Arrays'], ['objects', 'Objects'], ['strings', 'Strings'], ['algorithms', 'Algorithms'], ['classes', 'Classes']]
const topics: Record<ChallengeLanguage, Array<{ value: string; label: string }>> = {
  javascript: buildTopics([...fundamentals, ['array-methods', 'Array methods'], ['dom', 'DOM'], ['async', 'Async JavaScript'], ['apis', 'APIs'], ['components', 'Components'], ['state', 'State'], ['html', 'HTML'], ['css', 'CSS'], ['git', 'Git']]),
  typescript: buildTopics([...fundamentals, ['array-methods', 'Array methods'], ['dom', 'DOM'], ['async', 'Async TypeScript'], ['apis', 'APIs'], ['components', 'Components'], ['state', 'State'], ['html', 'HTML'], ['css', 'CSS'], ['git', 'Git']]),
  python: buildTopics(fundamentals), java: buildTopics(fundamentals), cpp: buildTopics(fundamentals.filter(([value]) => value !== 'objects')), csharp: buildTopics(fundamentals),
}
const labelFor = (options: Array<{ value: string; label: string }>, value: string) => options.find((option) => option.value === value)?.label ?? value

export function ChallengePage() {
  const [searchParams] = useSearchParams(); const roadmapStepId = searchParams.get('roadmapStepId'); const requestedTopic = searchParams.get('topic'); const [language, setLanguage] = useState<ChallengeLanguage>(() => { const stored = readLearnerProgress().preferredLanguage; return languages.some((item) => item.value === stored) ? stored as ChallengeLanguage : 'javascript' }); const [topic, setTopic] = useState(() => requestedTopic && topics.javascript.some((item) => item.value === requestedTopic) ? requestedTopic : readLearnerProgress().learningPreferences.topic || 'variables'); const [difficulty, setDifficulty] = useState<ChallengeDifficulty>(() => readLearnerProgress().learningPreferences.difficulty)
  const [challenge, setChallenge] = useState<AIChallengeResponse | null>(null); const [code, setCode] = useState(''); const [hints, setHints] = useState<AIHintResponse[]>([]); const [feedback, setFeedback] = useState<AIFeedbackResponse | null>(null)
  const [loading, setLoading] = useState<'challenge' | 'hint' | 'feedback' | null>(null); const [error, setError] = useState<{ action: 'challenge' | 'hint' | 'feedback'; message: string } | null>(null); const [solutionOpen, setSolutionOpen] = useState(false); const [solutionRevealed, setSolutionRevealed] = useState(false); const [explanation, setExplanation] = useState<{ content: string; context: 'challenge' | 'code'; label: string } | null>(null); const tutorRef = useRef<HTMLDivElement>(null)
  useEffect(() => { if (!requestedTopic || !topics[language].some((item) => item.value === requestedTopic)) setTopic(topics[language][0].value); const next = readLearnerProgress(); writeLearnerProgress({ ...next, preferredLanguage: language }) }, [language, requestedTopic]); useEffect(() => { if (hints.length || feedback) tutorRef.current?.focus() }, [hints, feedback])
  const request = { language, topic, difficulty }
  async function generate() { setLoading('challenge'); setError(null); try { const next = await aiService.generateChallenge(request); const challengeId = `${language}:${topic}:${next.title}`; const current = readLearnerProgress(); writeLearnerProgress({ ...current, preferredLanguage: language, learningPreferences: { topic, difficulty }, attemptedChallengeIds: current.attemptedChallengeIds.includes(challengeId) ? current.attemptedChallengeIds : [...current.attemptedChallengeIds, challengeId] }); setChallenge(next); setCode(next.starterCode); setHints([]); setFeedback(null) } catch (reason) { setError({ action: 'challenge', message: reason instanceof Error ? reason.message : 'We could not create a challenge right now.' }) } finally { setLoading(null) } }
  async function getHint() { if (!challenge) return; setLoading('hint'); setError(null); try { const hint = await aiService.generateHint({ ...request, code, hintLevel: Math.min(hints.length + 1, 3) as 1 | 2 | 3 }); setHints((current) => [...current, hint]) } catch (reason) { setError({ action: 'hint', message: reason instanceof Error ? reason.message : 'We could not get a hint right now.' }) } finally { setLoading(null) } }
  async function checkSolution() { if (!challenge) return; setLoading('feedback'); setError(null); try { const nextFeedback = await aiService.analyzeFeedback({ ...request, code, challenge: { title: challenge.title, description: challenge.description, evaluationGuidance: challenge.evaluationGuidance } }); setFeedback(nextFeedback); if (nextFeedback.correctness.toLowerCase().startsWith('correct')) { const challengeId = `${language}:${topic}:${challenge.title}`; const current = readLearnerProgress(); writeLearnerProgress({ ...current, currentStepId: roadmapStepId ?? current.currentStepId, completedChallengeIds: current.completedChallengeIds.includes(challengeId) ? current.completedChallengeIds : [...current.completedChallengeIds, challengeId], recentActivities: [{ id: challengeId, title: challenge.title, type: 'challenge' as const, completedAt: new Date().toISOString() }, ...current.recentActivities.filter((activity) => activity.id !== challengeId)].slice(0, 8) }) } } catch (reason) { setError({ action: 'feedback', message: reason instanceof Error ? reason.message : 'We could not review your work right now.' }) } finally { setLoading(null) } }
  function retry() { if (!error) return; if (error.action === 'challenge') void generate(); if (error.action === 'hint') void getHint(); if (error.action === 'feedback') void checkSolution() }
  if (!challenge) return <Configuration language={language} setLanguage={setLanguage} topic={topic} setTopic={setTopic} difficulty={difficulty} setDifficulty={setDifficulty} onGenerate={() => void generate()} loading={loading === 'challenge'} error={error?.action === 'challenge' ? error.message : null} onRetry={retry} />
  const languageConfig = languages.find((item) => item.value === language)!; const correct = feedback?.correctness.toLowerCase().startsWith('correct') ?? false
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><SectionHeader eyebrow="AI coding challenge" title={challenge.title} description={challenge.description} /><Button variant="outline" onClick={() => setChallenge(null)}>New challenge</Button></div><div className="mt-6 flex flex-wrap gap-2 text-sm"><Tag>{labelFor(languages, language)}</Tag><Tag>{labelFor(topics[language], topic)}</Tag><Tag>{difficulty}</Tag><Button size="sm" variant="outline" onClick={() => setExplanation({ content: challenge.description, context: 'challenge', label: 'Challenge instructions' })}><Sparkles size={15} aria-hidden="true" />Explain this</Button></div>{explanation && <div className="mt-6"><ExplanationPanel content={explanation.content} context={explanation.context} label={explanation.label} language={language} topic={topic} onClose={() => setExplanation(null)} /></div>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-6"><Card className="p-5"><h2 className="font-bold text-ink dark:text-white">Examples</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{challenge.testCases.map((testCase, index) => <div key={`${testCase.input}-${index}`} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><p><b>Input:</b> {testCase.input}</p><p className="mt-1"><b>Expected:</b> {testCase.expectedOutput}</p></div>)}</div><p className="mt-4 text-sm text-slate-600 dark:text-slate-300">Checks use AI analysis against this challenge’s guidance; CodePath AI never executes submitted code on its server.</p></Card>
      <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-800"><label className="font-bold text-ink dark:text-white">Your solution</label><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setExplanation({ content: code, context: 'code', label: 'Your code snippet' })}><Sparkles size={15} aria-hidden="true" />Explain this</Button><Button size="sm" variant="outline" onClick={() => setCode(challenge.starterCode)}><RotateCcw size={15} aria-hidden="true" />Reset code</Button><Button size="sm" variant="outline" onClick={() => { setSolutionRevealed(false); setSolutionOpen(true) }}>Show solution</Button><Button size="sm" onClick={() => void checkSolution()} disabled={loading !== null}><Send size={15} aria-hidden="true" />{loading === 'feedback' ? 'Reviewing…' : 'Run / Check solution'}</Button></div></div><div className="h-[430px]" aria-label="Code editor"><Editor height="100%" language={languageConfig.editor} value={code} onChange={(value) => setCode(value ?? '')} theme="vs-dark" options={{ minimap: { enabled: false }, fontSize: 14, automaticLayout: true, ariaLabel: 'Code editor. Write your solution here.' }} /></div></Card></div>
      <aside ref={tutorRef} tabIndex={-1} className="space-y-4 rounded-2xl border border-brand-200 bg-brand-50 p-5 outline-none dark:border-brand-900 dark:bg-brand-950" aria-label="AI tutor panel"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-600 text-white"><Sparkles size={18} aria-hidden="true" /></div><div><h2 className="font-bold text-ink dark:text-white">Need a nudge?</h2><p className="mt-1 text-sm text-slate-700 dark:text-slate-200">Ask your AI tutor for a progressively more specific hint.</p></div></div><Button className="w-full" variant="secondary" onClick={() => void getHint()} disabled={loading !== null}><Lightbulb size={16} aria-hidden="true" />{loading === 'hint' ? 'Thinking…' : 'Get hint'}</Button>{hints.map((hint, index) => <div key={`${hint.level}-${index}`} className="rounded-xl bg-white p-4 text-sm shadow-sm dark:bg-slate-900"><p className="font-semibold text-brand-700 dark:text-blue-300">Hint {index + 1}</p><p className="mt-2 text-slate-700 dark:text-slate-200">{hint.hint}</p><p className="mt-2 text-slate-600 dark:text-slate-300">{hint.explanation}</p></div>)}{loading === 'hint' && <TutorLoading label="Your tutor is considering your code…" />}{error?.action === 'hint' && <InlineError message={error.message} onRetry={retry} />}{feedback && <Feedback feedback={feedback} correct={correct} />}{loading === 'feedback' && <TutorLoading label="Reviewing your approach without running it…" />}{error?.action === 'feedback' && <InlineError message={error.message} onRetry={retry} />}</aside></div>
    <Modal open={solutionOpen} onClose={() => setSolutionOpen(false)} title="Reveal the solution?">{!solutionRevealed ? <><p>Try a hint first if you can. Revealing it is intentional.</p><div className="mt-5 flex justify-end gap-3"><Button variant="outline" onClick={() => setSolutionOpen(false)}>Keep trying</Button><Button onClick={() => setSolutionRevealed(true)}>Reveal solution</Button></div></> : challenge.solution ? <pre className="overflow-auto rounded-xl bg-slate-950 p-4 text-sm text-slate-100"><code>{challenge.solution}</code></pre> : <p>A full solution was not included for this challenge. Use another hint or generate a new exercise.</p>}</Modal></div>
}

function Configuration(props: { language: ChallengeLanguage; setLanguage: (value: ChallengeLanguage) => void; topic: string; setTopic: (value: string) => void; difficulty: ChallengeDifficulty; setDifficulty: (value: ChallengeDifficulty) => void; onGenerate: () => void; loading: boolean; error: string | null; onRetry: () => void }) { return <div className="mx-auto max-w-3xl"><SectionHeader eyebrow="Build by doing" title="AI coding challenges" description="Choose a focused exercise, then work with a supportive AI tutor when you want a nudge." /><Card className="mt-8 p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Language"><Select value={props.language} onChange={(event) => props.setLanguage(event.target.value as ChallengeLanguage)} aria-label="Programming language">{languages.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</Select></Field><Field label="Topic"><Select value={props.topic} onChange={(event) => props.setTopic(event.target.value)} aria-label="Challenge topic">{topics[props.language].map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</Select></Field><Field label="Difficulty"><Select value={props.difficulty} onChange={(event) => props.setDifficulty(event.target.value as ChallengeDifficulty)} aria-label="Challenge difficulty"><option value="beginner">Beginner</option><option value="easy">Easy</option><option value="intermediate">Intermediate</option></Select></Field></div><p className="mt-5 text-sm text-slate-600 dark:text-slate-300">Topics update to match the language you choose, so you only see relevant options.</p><Button size="lg" className="mt-6" onClick={props.onGenerate} disabled={props.loading}>{props.loading ? <><LoaderCircle className="animate-spin motion-reduce:animate-none" size={18} aria-hidden="true" />Creating your challenge…</> : <><Code2 size={18} aria-hidden="true" />Generate challenge</>}</Button>{props.loading && <p className="mt-4 text-sm text-slate-600 dark:text-slate-300" role="status">Designing an exercise tailored to your selections…</p>}{props.error && <div className="mt-5"><ErrorState title="Challenge generation paused" message={props.error} action={<Button onClick={props.onRetry}>Try again</Button>} /></div>}</Card><QuickExplain language={props.language} topic={props.topic} /></div> }
function QuickExplain({ language, topic }: { language: ChallengeLanguage; topic: string }) { const [content, setContent] = useState(''); const [kind, setKind] = useState<'term' | 'error'>('term'); const [open, setOpen] = useState(false); return <Card className="mt-6 p-5"><h2 className="font-bold text-ink dark:text-white">Something unfamiliar?</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Paste a term or error message and get a plain-language explanation.</p><div className="mt-4 grid gap-3 sm:grid-cols-[10rem_1fr_auto]"><Select value={kind} onChange={(event) => setKind(event.target.value as 'term' | 'error')} aria-label="What to explain"><option value="term">A term</option><option value="error">An error</option></Select><label className="sr-only" htmlFor="quick-explain">Term or error message</label><input id="quick-explain" value={content} onChange={(event) => setContent(event.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-ink dark:border-slate-600 dark:bg-slate-950 dark:text-white" placeholder="For example: undefined is not a function" /><Button variant="outline" disabled={!content.trim()} onClick={() => setOpen(true)}><Sparkles size={16} aria-hidden="true" />Explain this</Button></div>{open && <div className="mt-4"><ExplanationPanel content={content} context={kind} label={kind === 'error' ? 'Error message' : 'Programming term'} language={language} topic={topic} onClose={() => setOpen(false)} /></div>}</Card> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 font-semibold text-ink dark:text-white"><span>{label}</span>{children}</label> }
function Tag({ children }: { children: ReactNode }) { return <span className="rounded-full bg-slate-100 px-3 py-1 font-semibold capitalize text-slate-700 dark:bg-slate-800 dark:text-slate-200">{children}</span> }
function TutorLoading({ label }: { label: string }) { return <p role="status" className="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200"><LoaderCircle className="animate-spin motion-reduce:animate-none" size={16} aria-hidden="true" />{label}</p> }
function InlineError({ message, onRetry }: { message: string; onRetry: () => void }) { return <div role="alert" className="rounded-xl border border-red-200 bg-white p-4 text-sm text-red-900 dark:border-red-900 dark:bg-slate-900 dark:text-red-100"><AlertCircle className="inline" size={16} aria-hidden="true" /> <span>{message}</span><Button size="sm" className="mt-3" variant="outline" onClick={onRetry}>Try again</Button></div> }
function Feedback({ feedback, correct }: { feedback: AIFeedbackResponse; correct: boolean }) { const sections = [['What you did well', feedback.strengths], ['Problems found', [...feedback.likelyBugs, ...feedback.conceptualMistakes]], ['Explanation', [feedback.summary, ...feedback.improvements]], ['Suggested next step', [feedback.nextStep]]] as const; return <section className="rounded-xl bg-white p-4 shadow-sm dark:bg-slate-900" aria-live="polite"><div className="flex items-center gap-2 font-bold text-ink dark:text-white">{correct ? <CheckCircle2 className="text-emerald-600" aria-hidden="true" /> : <AlertCircle className="text-amber-600" aria-hidden="true" />}<span>{correct ? 'Correct' : 'Needs improvement'}</span></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{feedback.correctness}</p>{sections.map(([heading, values]) => <div className="mt-4" key={heading}><h3 className="text-sm font-bold text-ink dark:text-white">{heading}</h3><ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-slate-700 dark:text-slate-200">{values.length ? values.map((value, index) => <li key={index}>{value}</li>) : <li>No concerns identified yet.</li>}</ul></div>)}</section> }
