import { Award, BookOpen, CheckCircle2, ChevronRight, Code2, Compass, Route as RouteIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Card } from '@/components/ui/Card'
import { ProgressBar } from '@/components/ui/ProgressBar'
import { SectionHeader } from '@/components/ui/SectionHeader'
import { roadmaps } from '@/data/roadmaps'
import { useLearnerProgress } from '@/hooks/useLearnerProgress'

type LearnerProgress = ReturnType<typeof useLearnerProgress>['progress']

export function ProgressPage() {
	const { progress } = useLearnerProgress()
	const completedSteps = Object.values(progress.completedStepIds).reduce((total, steps) => total + steps.length, 0)
	const hasStarted = completedSteps > 0 || progress.attemptedChallengeIds.length > 0 || progress.exploredResourceIds.length > 0
	return <div><SectionHeader eyebrow="Your journey" title="See your learning progress" description="Your activity is saved locally on this device, so you can keep learning at your own pace." />{!hasStarted ? <EmptyProgress /> : <div className="mt-8 space-y-8"><Summary progress={progress} completedSteps={completedSteps} /><div className="grid gap-8 xl:grid-cols-[minmax(0,1.4fr)_minmax(18rem,0.6fr)]"><LearningProgress progress={progress} /><Achievements progress={progress} completedSteps={completedSteps} /></div><RecentActivities progress={progress} /></div>}</div>
}

function EmptyProgress() { return <Card className="mt-8 border-brand-200 bg-brand-50 p-7 dark:border-brand-900 dark:bg-brand-950 sm:p-10"><div className="max-w-2xl"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-600 text-white"><Compass aria-hidden="true" size={24} /></div><h2 className="mt-6 text-2xl font-bold text-ink dark:text-white">You haven't started learning yet.</h2><p className="mt-3 leading-7 text-slate-700 dark:text-slate-200">Pick a guided path or try a small coding exercise. Your progress will appear here as you learn.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/roadmaps" className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 font-semibold text-white hover:bg-brand-700">Choose a roadmap <ChevronRight size={17} aria-hidden="true" /></Link><Link to="/challenges" className="inline-flex items-center gap-2 rounded-xl border border-brand-300 px-4 py-2.5 font-semibold text-brand-800 hover:bg-white dark:border-brand-700 dark:text-blue-200 dark:hover:bg-slate-900">Try your first challenge <Code2 size={17} aria-hidden="true" /></Link></div></div></Card> }

function Summary({ progress, completedSteps }: { progress: LearnerProgress; completedSteps: number }) { const roadmap = roadmaps.find((item) => item.id === progress.currentRoadmapId); const currentStep = roadmap?.steps.find((step) => !progress.completedStepIds[roadmap.id]?.includes(step.id)); const roadmapProgress = roadmap ? Math.round((progress.completedStepIds[roadmap.id]?.length ?? 0) / roadmap.steps.length * 100) : 0; return <div className="grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(15rem,0.65fr)]"><Card className="p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-brand-700 dark:text-blue-300">Current roadmap</p><h2 className="mt-2 text-2xl font-bold text-ink dark:text-white">{roadmap?.title ?? 'Choose your next roadmap'}</h2><p className="mt-2 text-slate-600 dark:text-slate-300">{roadmap ? currentStep ? `Next: ${currentStep.title}` : 'All steps complete. Nice work.' : 'Start a guided sequence to build steady momentum.'}</p></div><RouteIcon className="text-brand-600" aria-hidden="true" /></div>{roadmap ? <><div className="mt-6"><ProgressBar label="Roadmap progress" value={roadmapProgress} /></div><Link to={`/roadmaps/${roadmap.id}`} className="mt-6 inline-flex items-center gap-2 font-semibold text-brand-700 dark:text-blue-300">Continue {currentStep ? `step ${roadmap.steps.indexOf(currentStep) + 1}` : 'roadmap'} <ChevronRight size={17} aria-hidden="true" /></Link></> : <Link to="/roadmaps" className="mt-6 inline-flex items-center gap-2 font-semibold text-brand-700 dark:text-blue-300">Browse roadmaps <ChevronRight size={17} aria-hidden="true" /></Link>}</Card><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1"><Metric icon={<Code2 aria-hidden="true" />} value={progress.completedChallengeIds.length} label="Challenges completed" /><Metric icon={<CheckCircle2 aria-hidden="true" />} value={completedSteps} label="Roadmap steps completed" /><Metric icon={<BookOpen aria-hidden="true" />} value={progress.exploredResourceIds.length} label="Resources explored" /></div></div> }

function LearningProgress({ progress }: { progress: LearnerProgress }) { const roadmap = roadmaps.find((item) => item.id === progress.currentRoadmapId); const completed = roadmap ? progress.completedStepIds[roadmap.id] ?? [] : []; return <section><h2 className="text-xl font-bold text-ink dark:text-white">Learning progress</h2><p className="mt-1 text-slate-600 dark:text-slate-300">A clear view of what you have completed and what comes next.</p>{roadmap ? <Card className="mt-5 p-6"><ProgressBar label={`${roadmap.title} progress`} value={Math.round(completed.length / roadmap.steps.length * 100)} /><ol className="mt-6 space-y-3" aria-label={`${roadmap.title} progress`}>{roadmap.steps.map((step, index) => <li key={step.id} className="flex items-start gap-3"><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full border-2 text-xs font-bold ${completed.includes(step.id) ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-300 text-slate-600 dark:border-slate-600 dark:text-slate-300'}`}>{completed.includes(step.id) ? <CheckCircle2 size={14} aria-hidden="true" /> : index + 1}</span><span className={completed.includes(step.id) ? 'text-slate-500 line-through dark:text-slate-400' : 'font-semibold text-ink dark:text-white'}>{step.title}</span></li>)}</ol></Card> : <Card className="mt-5 p-6"><p className="text-slate-600 dark:text-slate-300">Choose a roadmap to see your learning path here.</p><Link to="/roadmaps" className="mt-4 inline-flex items-center gap-2 font-semibold text-brand-700 dark:text-blue-300">Explore roadmaps <ChevronRight size={17} aria-hidden="true" /></Link></Card>}</section> }

function Achievements({ progress, completedSteps }: { progress: LearnerProgress; completedSteps: number }) { const achievements = [{ title: 'First Challenge', description: 'Complete your first coding challenge.', earned: progress.completedChallengeIds.length > 0 }, { title: 'First Roadmap Step', description: 'Complete a step in a learning roadmap.', earned: completedSteps > 0 }, { title: '5 Challenges Completed', description: 'Complete five coding challenges.', earned: progress.completedChallengeIds.length >= 5 }, { title: 'Roadmap Started', description: 'Begin your first roadmap.', earned: Object.keys(progress.completedStepIds).length > 0 }]; return <section><h2 className="text-xl font-bold text-ink dark:text-white">Achievements</h2><p className="mt-1 text-slate-600 dark:text-slate-300">Small milestones that mark real learning progress.</p><div className="mt-5 space-y-3">{achievements.map((achievement) => <Card key={achievement.title} className={`p-4 ${achievement.earned ? 'border-emerald-200 dark:border-emerald-900' : 'opacity-70'}`}><div className="flex gap-3"><Award className={achievement.earned ? 'shrink-0 text-amber-500' : 'shrink-0 text-slate-400'} aria-hidden="true" /><div><h3 className="font-bold text-ink dark:text-white">{achievement.title}</h3><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{achievement.description}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{achievement.earned ? 'Earned' : 'Not yet earned'}</p></div></div></Card>)}</div></section> }

function RecentActivities({ progress }: { progress: LearnerProgress }) { return <section><h2 className="text-xl font-bold text-ink dark:text-white">Recent completed activities</h2>{progress.recentActivities.length ? <ul className="mt-5 grid gap-3 md:grid-cols-2">{progress.recentActivities.map((activity) => <li key={`${activity.type}-${activity.id}`}><Card className="flex items-center gap-3 p-4"><CheckCircle2 className="shrink-0 text-emerald-600" aria-hidden="true" /><div><p className="font-semibold text-ink dark:text-white">{activity.title}</p><p className="mt-1 text-sm capitalize text-slate-500 dark:text-slate-400">{activity.type} completed</p></div></Card></li>)}</ul> : <Card className="mt-5 p-5 text-slate-600 dark:text-slate-300">Completed activities will appear here as you work through your path.</Card>}</section> }

function Metric({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <Card className="p-5"><div className="text-brand-700 dark:text-blue-300">{icon}</div><p className="mt-4 text-3xl font-bold text-ink dark:text-white">{value}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{label}</p></Card> }
