import { Check, ChevronLeft, ChevronRight, Circle, Clock, ExternalLink, PlayCircle, Puzzle, BookOpen, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { EmptyState } from '@/components/ui/EmptyState'
import { ExplanationPanel } from '@/components/ExplanationPanel'
import { ProgressBar } from '@/components/ui/ProgressBar'
import { Tabs } from '@/components/ui/Tabs'
import { getResourcesForRoadmapStep, getRoadmapById } from '@/data/selectors'
import { useRoadmapProgress } from '@/hooks/useRoadmapProgress'
import type { Resource, Roadmap, RoadmapStep } from '@/types/content'
import { recordResourceExplored } from '@/lib/learnerProgress'
import { formatLearningTime } from '@/utils/format'

export function RoadmapDetailPage() { const { roadmapId } = useParams(); const roadmap = roadmapId ? getRoadmapById(roadmapId) : undefined; return roadmap ? <RoadmapDetail roadmap={roadmap} /> : <Navigate to="/roadmaps" replace /> }
function RoadmapDetail({ roadmap }: { roadmap: Roadmap }) { const { progress, isComplete, toggleStep } = useRoadmapProgress(roadmap.id, roadmap.steps.map((step) => step.id)); const duration = roadmap.steps.reduce((sum, step) => sum + step.estimatedMinutes, 0); return <div><Link to="/roadmaps" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-700 dark:text-blue-300"><ChevronLeft size={17} aria-hidden="true" /> All roadmaps</Link><section className="mt-5 rounded-3xl bg-ink p-7 text-white sm:p-10"><p className="text-sm font-bold tracking-wide text-blue-200">{roadmap.category.toUpperCase()}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{roadmap.title}</h1><p className="mt-4 max-w-2xl text-lg leading-7 text-slate-300">{roadmap.description}</p><div className="mt-7 grid gap-5 sm:grid-cols-[auto_auto_minmax(14rem,1fr)] sm:items-center"><p className="text-sm text-slate-200"><span className="font-bold text-white">Beginner</span><br />Level</p><p className="text-sm text-slate-200"><span className="font-bold text-white">{formatLearningTime(duration)}</span><br />Estimated time</p><ProgressBar label="Roadmap progress" value={progress} /></div></section><section className="mt-10"><h2 className="text-2xl font-bold text-ink dark:text-white">Your learning path</h2><p className="mt-2 text-slate-600 dark:text-slate-300">Select any step to reveal learning materials and practice ideas. Your completed steps are saved on this device.</p><ol className="mt-8 space-y-4" aria-label={`${roadmap.title} steps`}>{roadmap.steps.map((step, index) => <li key={step.id} className="relative pl-0 sm:pl-16"><div className="mb-2 flex h-10 w-10 items-center justify-center rounded-full border-2 border-brand-600 bg-white font-bold text-brand-700 dark:bg-slate-950 dark:text-blue-200 sm:absolute sm:left-0 sm:top-5" aria-label={`Step ${index + 1}${isComplete(step.id) ? ', completed' : ''}`}>{isComplete(step.id) ? <Check aria-hidden="true" size={19} /> : index + 1}</div><StepNode step={step} index={index} complete={isComplete(step.id)} onToggle={() => toggleStep(step.id)} nextStep={roadmap.steps[index + 1]} /></li>)}</ol></section></div> }
function StepNode({ step, index, complete, onToggle, nextStep }: { step: RoadmapStep; index: number; complete: boolean; onToggle: () => void; nextStep?: RoadmapStep }) { const resources = getResourcesForRoadmapStep(step.id); const videos = resources.filter((resource) => resource.type === 'youtube-channel' || resource.type === 'youtube-video'); const learnResources = resources.filter((resource) => !videos.includes(resource)); return <Card id={step.id} className="overflow-hidden"><details open={index === 0}><summary className="cursor-pointer list-none p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><Badge tone={complete ? 'green' : 'blue'}>{complete ? 'Completed' : step.difficulty}</Badge><span className="flex items-center gap-1 text-sm text-slate-500 dark:text-slate-400"><Clock size={15} aria-hidden="true" /> {formatLearningTime(step.estimatedMinutes)}</span></div><h3 className="mt-3 text-xl font-bold text-ink dark:text-white">Step {index + 1}: {step.title}</h3><p className="mt-2 max-w-2xl leading-6 text-slate-600 dark:text-slate-300">{step.description}</p></div><span className="text-sm font-semibold text-brand-700 dark:text-blue-300">{complete ? 'Review step' : 'Open step'}</span></div></summary><div className="border-t border-slate-200 p-5 dark:border-slate-800 sm:p-6"><Tabs tabs={[{ id: 'learn', label: 'Learn', content: <LearnSection step={step} resources={learnResources} /> }, { id: 'watch', label: 'Watch', content: <WatchSection resources={videos} /> }, { id: 'practice', label: 'Practice', content: <PracticeSection topics={step.challengeTopics} stepId={step.id} /> }]} /><div className="mt-7 flex flex-col gap-3 border-t border-slate-200 pt-5 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><Button variant={complete ? 'outline' : 'primary'} onClick={onToggle} aria-pressed={complete}>{complete ? <><Check size={17} aria-hidden="true" /> Mark incomplete</> : <><Circle size={17} aria-hidden="true" /> Mark step complete</>}</Button>{nextStep ? <a href={`#${nextStep.id}`} className="inline-flex items-center gap-1 font-semibold text-brand-700 dark:text-blue-300">Next: {nextStep.title}<ChevronRight size={17} aria-hidden="true" /></a> : <span className="font-semibold text-emerald-700 dark:text-emerald-300">You’ve reached the final step.</span>}</div></div></details></Card> }
function LearnSection({ step, resources }: { step: RoadmapStep; resources: Resource[] }) { const [explanationOpen, setExplanationOpen] = useState(false); return <div><div className="flex flex-wrap items-start justify-between gap-3"><p className="leading-7 text-slate-600 dark:text-slate-300">This step focuses on {step.concepts.join(', ')}. Work through the material below, then try a small exercise to make the concepts stick.</p><Button size="sm" variant="outline" onClick={() => setExplanationOpen(true)}><Sparkles size={15} aria-hidden="true" /> Explain this step</Button></div>{explanationOpen && <div className="mt-5"><ExplanationPanel content={`${step.title}. ${step.description} Key concepts: ${step.concepts.join(', ')}.`} context="concept" label={`${step.title} explained`} onClose={() => setExplanationOpen(false)} /></div>}<h4 className="mt-5 flex items-center gap-2 font-bold text-ink dark:text-white"><BookOpen size={18} aria-hidden="true" /> Related resources</h4>{resources.length ? <ResourceLinks resources={resources} /> : <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">Resource recommendations for this step are coming soon.</p>}</div> }
function WatchSection({ resources }: { resources: Resource[] }) { return <div>{resources.length ? <ResourceLinks resources={resources} /> : <EmptyState icon={<PlayCircle aria-hidden="true" />} title="No video selected yet" message="This step has reading and practice resources. Video recommendations will be added when they are reviewed." />}</div> }
function PracticeSection({ topics, stepId }: { topics: string[]; stepId: string }) { const topic = topics[0] ?? 'variables'; return <div><p className="flex items-center gap-2 text-slate-600 dark:text-slate-300"><Puzzle size={18} aria-hidden="true" /> Build confidence by practising these focused topics:</p><ul className="mt-4 flex flex-wrap gap-2">{topics.map((item) => <li key={item}><Badge tone="amber">{item}</Badge></li>)}</ul><Link className="mt-6 inline-flex items-center gap-1 font-semibold text-brand-700 dark:text-blue-300" to={`/challenges?topic=${encodeURIComponent(topic)}&roadmapStepId=${encodeURIComponent(stepId)}`}>Practice {topic} with a challenge <ChevronRight size={17} aria-hidden="true" /></Link></div> }
function ResourceLinks({ resources }: { resources: Resource[] }) { return <ul className="mt-3 space-y-3">{resources.map((resource) => <li key={resource.id}><a className="flex items-start justify-between gap-4 rounded-xl border border-slate-200 p-4 hover:border-brand-400 dark:border-slate-700 dark:hover:border-brand-500" href={resource.url} target="_blank" rel="noreferrer" onClick={() => recordResourceExplored(resource.id)}><span><span className="font-semibold text-ink dark:text-white">{resource.title}</span><span className="mt-1 block text-sm text-slate-600 dark:text-slate-300">{resource.provider} · {resource.type.replace('-', ' ')}</span></span><ExternalLink className="shrink-0 text-brand-700 dark:text-blue-300" size={17} aria-hidden="true" /></a></li>)}</ul> }
