import { LoaderCircle, Sparkles, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Button } from '@/components/ui/Button'
import { Select } from '@/components/ui/Select'
import { aiService } from '@/services/ai'
import type { AIExplainResponse, ChallengeLanguage, ExplanationLevel } from '@/types/ai'

export function ExplanationPanel({ content, language, topic, context, label, onClose }: { content: string; language?: ChallengeLanguage; topic?: string; context: 'concept' | 'challenge' | 'code' | 'error' | 'term'; label: string; onClose: () => void }) {
  const [level, setLevel] = useState<ExplanationLevel>('beginner'); const [result, setResult] = useState<AIExplainResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const panelRef = useRef<HTMLElement>(null)
  async function explain(nextLevel = level) { setLoading(true); setError(null); try { setResult(await aiService.explain({ content, language, topic, context, level: nextLevel })); setLevel(nextLevel) } catch (reason) { setError(reason instanceof Error ? reason.message : 'We could not create an explanation right now.') } finally { setLoading(false) } }
  useEffect(() => { setLoading(true); setError(null); void aiService.explain({ content, language, topic, context, level: 'beginner' }).then((next) => { setResult(next); setLevel('beginner') }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'We could not create an explanation right now.')).finally(() => setLoading(false)); panelRef.current?.focus() }, [content, context, language, topic])
  return <section ref={panelRef} tabIndex={-1} className="surface relative p-5 outline-none" aria-labelledby="explanation-title" aria-live="polite"><button type="button" onClick={onClose} className="absolute right-3 top-3 rounded-lg p-2 text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800" aria-label="Close explanation"><X size={18} aria-hidden="true" /></button><div className="flex items-start gap-3 pr-8"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-600 text-white"><Sparkles size={18} aria-hidden="true" /></div><div><h2 id="explanation-title" className="font-bold text-ink dark:text-white">Explain with AI</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{label}</p></div></div><div className="mt-4 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-sm font-semibold text-ink dark:text-white"><span>Explanation level</span><Select value={level} onChange={(event) => void explain(event.target.value as ExplanationLevel)} disabled={loading}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="technical">Technical</option></Select></label><Button size="sm" variant="outline" disabled={loading} onClick={() => void explain('beginner')}>Make it simpler</Button></div>{loading && <p role="status" className="mt-5 flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300"><LoaderCircle className="animate-spin motion-reduce:animate-none" size={16} aria-hidden="true" />Creating a clear explanation…</p>}{error && <div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900 dark:border-red-900 dark:bg-red-950 dark:text-red-100"><p>{error}</p><Button className="mt-3" size="sm" variant="outline" onClick={() => void explain()}>Try again</Button></div>}{result && !loading && <div className="mt-5 space-y-4 text-sm leading-6 text-slate-700 dark:text-slate-200"><p>{result.explanation}</p>{result.simpleExample && <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><h3 className="font-bold text-ink dark:text-white">Small example</h3><p className="mt-1 whitespace-pre-wrap">{result.simpleExample}</p></div>}{result.keyTerms.length > 0 && <div><h3 className="font-bold text-ink dark:text-white">Words to know</h3><dl className="mt-2 space-y-2">{result.keyTerms.map(({ term, meaning }) => <div key={term}><dt className="font-semibold">{term}</dt><dd>{meaning}</dd></div>)}</dl></div>}</div>}</section>
}
