import { BookOpen, Code2, Compass, LayoutDashboard, Library, Menu, Moon, Sparkles, Sun, X } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { buttonStyles } from '@/utils/buttonStyles'
import { Tooltip } from '@/components/ui/Tooltip'
import { useTheme } from '@/hooks/useTheme'
import { AccessibilityPreferences } from '@/components/AccessibilityPreferences'

const links = [{ to: '/', label: 'Home', icon: LayoutDashboard, end: true }, { to: '/challenges', label: 'Challenges', icon: Code2 }, { to: '/roadmaps', label: 'Roadmaps', icon: Compass }, { to: '/resources', label: 'Resources', icon: Library }, { to: '/progress', label: 'Progress', icon: BookOpen }]
export function AppLayout() {
  const [open, setOpen] = useState(false); const { theme, toggleTheme } = useTheme()
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[60] focus:rounded-lg focus:bg-white focus:px-4 focus:py-3 focus:font-semibold focus:text-ink">Skip to main content</a><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur dark:border-slate-800 dark:bg-slate-950/95"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><NavLink to="/" className="flex shrink-0 items-center gap-2 font-bold text-ink dark:text-white" aria-label="CodePath AI home"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-600 text-white"><Code2 aria-hidden="true" size={20} /></span><span className="hidden sm:inline">CodePath <span className="text-brand-600 dark:text-blue-300">AI</span></span></NavLink><nav className="hidden flex-1 items-center justify-center gap-1 lg:flex" aria-label="Primary navigation"><NavigationLinks /></nav><div className="ml-auto flex items-center gap-1"><Tooltip label={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`}><button type="button" onClick={toggleTheme} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800" aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`}>{theme === 'light' ? <Moon size={19} aria-hidden="true" /> : <Sun size={19} aria-hidden="true" />}</button></Tooltip><AccessibilityPreferences /><NavLink to="/challenges" className={`${buttonStyles({ size: 'sm' })} hidden sm:inline-flex`}><Sparkles size={16} aria-hidden="true" /> Start learning</NavLink><button onClick={() => setOpen((value) => !value)} className="rounded-lg p-2 text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800 lg:hidden" aria-label="Toggle navigation menu" aria-expanded={open}>{open ? <X aria-hidden="true" /> : <Menu aria-hidden="true" />}</button></div></div>{open && <nav className="border-t border-slate-200 px-4 py-3 dark:border-slate-800 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1"><NavigationLinks onNavigate={() => setOpen(false)} /></div></nav>}</header><main id="main-content" className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:py-12"><Outlet /></main></div>
}
function NavigationLinks({ onNavigate }: { onNavigate?: () => void }) { return <>{links.map(({ to, label, icon: Icon, end }) => <NavLink key={to} to={to} end={end} onClick={onNavigate} className={({ isActive }) => `flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition-colors ${isActive ? 'bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-blue-200' : 'text-slate-600 hover:bg-slate-100 hover:text-ink dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white'}`}><Icon size={17} aria-hidden="true" />{label}</NavLink>)}</> }
