import type { AIFeedbackResponse, AIHintResponse, AIChallengeResponse, AIExplainResponse } from '../../src/types/ai'
import { allowedTopicsByLanguage, supportedLanguages, supportedTopics } from './types'
import type { ChallengeInput, ExplainInput, FeedbackInput, HintInput, SupportedLanguage, SupportedTopic } from './types'

const difficulties = new Set(['beginner', 'easy', 'intermediate'])
const isObject = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value)
const text = (value: unknown, max: number) => typeof value === 'string' && value.trim().length > 0 && value.length <= max ? value.trim() : null
const language = (value: unknown): SupportedLanguage | null => typeof value === 'string' && (supportedLanguages as readonly string[]).includes(value) ? value as SupportedLanguage : null
const topic = (value: unknown): SupportedTopic | null => typeof value === 'string' && (supportedTopics as readonly string[]).includes(value) ? value as SupportedTopic : null
const difficulty = (value: unknown) => typeof value === 'string' && difficulties.has(value) ? value as ChallengeInput['difficulty'] : null
export function validateChallengeInput(body: unknown): ChallengeInput | null { if (!isObject(body)) return null; const validLanguage = language(body.language); const validTopic = topic(body.topic); const validDifficulty = difficulty(body.difficulty); if (!validLanguage || !validTopic || !validDifficulty || !allowedTopicsByLanguage[validLanguage].includes(validTopic)) return null; if (body.context === undefined) return { language: validLanguage, topic: validTopic, difficulty: validDifficulty }; const context = text(body.context, 1_200); return context ? { language: validLanguage, topic: validTopic, difficulty: validDifficulty, context } : null }
export function validateHintInput(body: unknown): HintInput | null { const base = validateChallengeInput(body); if (!base || !isObject(body)) return null; const code = text(body.code, 8_000); const hintLevel = body.hintLevel; return code && (hintLevel === 1 || hintLevel === 2 || hintLevel === 3) ? { ...base, code, hintLevel } : null }
export function validateFeedbackInput(body: unknown): FeedbackInput | null { const base = validateChallengeInput(body); if (!base || !isObject(body) || !isObject(body.challenge)) return null; const code = text(body.code, 12_000); const title = text(body.challenge.title, 120); const description = text(body.challenge.description, 1_500); const evaluationGuidance = text(body.challenge.evaluationGuidance, 800); return code && title && description && evaluationGuidance ? { ...base, code, challenge: { title, description, evaluationGuidance } } : null }
export function validateExplainInput(body: unknown): ExplainInput | null { if (!isObject(body)) return null; const content = text(body.content, 8_000); const level = body.level === 'beginner' || body.level === 'intermediate' || body.level === 'technical' ? body.level : null; const validLanguage = body.language === undefined ? undefined : language(body.language); const validTopic = body.topic === undefined ? undefined : topic(body.topic); const context = body.context === undefined ? undefined : body.context; if (!content || !level || (body.language !== undefined && !validLanguage) || (body.topic !== undefined && !validTopic) || (context !== undefined && !['concept', 'challenge', 'code', 'error', 'term'].includes(context as string))) return null; return { content, level, language: validLanguage ?? undefined, topic: validTopic ?? undefined, context: context as ExplainInput['context'] } }
const list = (value: unknown, maxItems: number, maxItemLength: number) => Array.isArray(value) && value.length <= maxItems && value.every((item) => text(item, maxItemLength)) ? value.map((item) => (item as string).trim()) : null
const displayValue = (value: unknown, maxLength: number) => { if (typeof value === 'string') return value.trim().slice(0, maxLength) || null; if (typeof value === 'number' || typeof value === 'boolean' || value === null) return String(value); try { const serialized = JSON.stringify(value); return serialized && serialized.length <= maxLength ? serialized : null } catch { return null } }
export function parseChallengeResponse(value: unknown): AIChallengeResponse | null { if (!isObject(value)) return null; const title = text(value.title, 120); const description = text(value.description, 1_500); const starterCode = text(value.starterCode, 4_000); const expectedConcepts = list(value.expectedConcepts, 8, 60); const hints = list(value.hints, 3, 300); const evaluationGuidance = text(value.evaluationGuidance, 800); const testCases = Array.isArray(value.testCases) && value.testCases.length <= 5 && value.testCases.every((item) => isObject(item) && displayValue(item.input, 300) && displayValue(item.expectedOutput, 500)) ? value.testCases.map((item) => ({ input: displayValue(item.input, 300) as string, expectedOutput: displayValue(item.expectedOutput, 500) as string })) : null; return title && description && starterCode && expectedConcepts && hints && evaluationGuidance && testCases ? { title, description, starterCode, expectedConcepts, hints, evaluationGuidance, testCases, solution: typeof value.solution === 'string' && value.solution.length <= 5_000 ? value.solution : undefined } : null }
export function parseHintResponse(value: unknown): AIHintResponse | null { if (!isObject(value)) return null; const hint = text(value.hint, 600); const explanation = text(value.explanation, 600); return hint && explanation && (value.level === 1 || value.level === 2 || value.level === 3) ? { hint, explanation, level: value.level } : null }
export function parseFeedbackResponse(value: unknown): AIFeedbackResponse | null { if (!isObject(value)) return null; const summary = text(value.summary, 900); const correctness = text(value.correctness, 600); const strengths = list(value.strengths, 5, 300); const likelyBugs = list(value.likelyBugs, 5, 300); const conceptualMistakes = list(value.conceptualMistakes, 5, 300); const improvements = list(value.improvements, 5, 300); const nextStep = text(value.nextStep, 300); return summary && correctness && strengths && likelyBugs && conceptualMistakes && improvements && nextStep ? { summary, correctness, strengths, likelyBugs, conceptualMistakes, improvements, nextStep } : null }
export function parseExplainResponse(value: unknown): AIExplainResponse | null { if (!isObject(value)) return null; const explanation = text(value.explanation, 2_400); const simpleExample = value.simpleExample === undefined ? undefined : text(value.simpleExample, 800); const keyTerms = Array.isArray(value.keyTerms) && value.keyTerms.length <= 6 && value.keyTerms.every((item) => isObject(item) && text(item.term, 80) && text(item.meaning, 240)) ? value.keyTerms.map((item) => ({ term: (item.term as string).trim(), meaning: (item.meaning as string).trim() })) : null; const level = value.level === 'beginner' || value.level === 'intermediate' || value.level === 'technical' ? value.level : null; return explanation && keyTerms && level ? { explanation, keyTerms, simpleExample: simpleExample ?? undefined, level } : null }
